import { slugifyTitle } from './create.ts';
import { AMENDMENTS_DIR } from './pending.ts';
import type { VeriDocument } from './types.ts';

/**
 * The shell emitter (REQ-040, DEC-125, WO-135): the half that makes a method
 * document reachable from a harness.
 *
 * DEC-125 splits the skill library in two. The *method* — what a gate asks,
 * what it may file, how it hands off — is a Veri document under
 * `veri/methods/` (DEC-130). The *invocation shell* is the small
 * harness-native file that makes the gate discoverable and triggerable, and
 * it is generated as a thin pointer into the method: a trigger description
 * plus a pointer, and no coaching content. That is DEC-018's rule for
 * harness files, one level down.
 *
 * Everything here is pure. It reads loaded documents and shells the host
 * collected, and returns the content that should be on disk plus the plan to
 * get there; it opens no file and knows no absolute path (DEC-040). The CLI
 * owns the writes, and WO-136's drift comparator will read the same emitter
 * so "what its method would emit now" has exactly one definition.
 */

/**
 * The default tier, verbatim from [[REQ-040]]'s enumerated acceptance
 * criterion — wayfinder, product-discovery, evidence-intake, define, decide,
 * plan-work, implement, did-it-work, health.
 *
 * The requirement's list is the authority and this constant is its
 * transcription. SRC-060's body cannot be counted for this: its own
 * "Editorial notes" section records two counting errors in the proposal it
 * preserves, and says in as many words that anything turning on tiering
 * reads REQ-040's list instead. The other five methods SRC-060 names are
 * advanced: they ship as method documents and get no shell unless asked for.
 */
export const DEFAULT_SKILL_SLUGS: readonly string[] = [
  'wayfinder',
  'product-discovery',
  'evidence-intake',
  'define',
  'decide',
  'plan-work',
  'implement',
  'did-it-work',
  'health',
];

/** The user-facing name DEC-125 fixes for everything a user types, including
    the skill prefix. `@verikb` stays an npm-scope artifact and never leaks. */
export const SKILL_PREFIX = 'veri';

/**
 * The line that marks a shell as generated. It is what makes removal safe:
 * `veri skills install` only ever deletes a file carrying this marker, so a
 * hand-authored skill that happens to sit in the same directory is never
 * touched. It is also the first thing WO-136's drift check can key on.
 */
export const SHELL_MARKER = '<!-- generated by `veri skills install` — do not edit; edit the method document instead -->';

/**
 * The stable slug of a method: what its skill is called, and what tiering is
 * read against.
 *
 * `upstream:` first, because DEC-130 makes it the one field that survives the
 * edits a project is invited to make — ids are minted on demand, titles and
 * filenames are the user's. A project-authored method has no `upstream:`, so
 * its own title is the only stable thing it has: the `veri:<name>` token the
 * shipped methods lead with is used when present, and otherwise the title is
 * slugified whole.
 */
export function methodSlug(doc: VeriDocument): string {
  const upstream = doc.upstream;
  if (upstream !== undefined && upstream.trim() !== '') {
    const tail = upstream.trim().split('/').filter((part) => part !== '').pop();
    if (tail !== undefined) return slugifyTitle(tail);
  }
  const titled = /^\s*veri:([a-z][a-z0-9-]*)/.exec(doc.title);
  if (titled !== null) return titled[1];
  return slugifyTitle(doc.title);
}

/** The skill name a shell is installed under: `veri-<slug>`. Harnesses name
    skills by directory and none of them accept a colon, so the prefix that
    reads `veri:plan-work` to a user is hyphenated on disk. */
export function skillName(doc: VeriDocument): string {
  return `${SKILL_PREFIX}-${methodSlug(doc)}`;
}

/**
 * Whether a method is in the default tier — the nine REQ-040 enumerates,
 * plus every method the project authored itself.
 *
 * A method with no `upstream:` is the project's own (DEC-130): somebody wrote
 * it deliberately into their own `veri/methods/` and approved it, which is a
 * clearer statement of intent than any list Veri ships. The tier exists to
 * keep Veri's own five advanced gates out of a default install, not to
 * second-guess the project.
 */
export function isDefaultTier(doc: VeriDocument): boolean {
  if (doc.upstream === undefined || doc.upstream.trim() === '') return true;
  return DEFAULT_SKILL_SLUGS.includes(methodSlug(doc));
}

/** A method a shell may be emitted for: DEC-130 says `accepted` and only
    `accepted`, so a draft can never trigger before it has been read. */
export function isEmittable(doc: VeriDocument): boolean {
  return doc.type === 'method' && doc.status === 'accepted';
}

/** One emitted shell: where it goes, and exactly what belongs in it. */
export interface SkillShell {
  /** Repo-root-relative, forward slashes — outside `veri/` by definition. */
  path: string;
  /** The skill name the harness will show. */
  name: string;
  /** The method this points at. */
  methodId: string;
  content: string;
}

/**
 * One harness's shell format. DEC-125 asks for a single interface with Claude
 * Code as its first implementation, so that a second harness is a new emitter
 * rather than a fork of the library's content: nothing below the interface
 * knows anything about a method except the four fields it reads, and the
 * method text itself lives in `veri/` where every harness reaches it through
 * the context package.
 */
export interface SkillEmitter {
  /** Harness id, as a user names it on the command line. */
  readonly harness: string;
  /** The directory this emitter owns, repo-root-relative. */
  readonly directory: string;
  /** Where this method's shell goes. */
  shellPath(doc: VeriDocument): string;
  /** The shell's full content — a pointer, never coaching. */
  emit(doc: VeriDocument): SkillShell;
  /** Whether a collected path is one this emitter could have written. */
  owns(path: string): boolean;
}

/** A YAML double-quoted scalar. JSON's string escaping is a strict subset of
    YAML's, so this round-trips the description byte for byte on one line —
    which is what makes the emitted shell deterministic, and therefore what
    makes idempotence and WO-136's drift comparison decidable. */
function yamlString(value: string): string {
  return JSON.stringify(value);
}

const CLAUDE_SKILLS_DIR = '.claude/skills';

/**
 * Claude Code's `SKILL.md` under `.claude/skills/<name>/`.
 *
 * The body is a pointer and a refusal rule, and nothing else. It names the
 * method's id and file so the agent can fetch the coaching through the MCP
 * surface (DEC-125: skills reach Veri only through tool calls), and it names
 * the tools the method declares so a session missing one refuses with a
 * repair instruction instead of interviewing a user it cannot file for. No
 * section of the method body appears here — that is the whole point of the
 * split, and the reason a stale shell is a stale pointer rather than stale
 * coaching.
 */
export const claudeCodeEmitter: SkillEmitter = {
  harness: 'claude-code',
  directory: CLAUDE_SKILLS_DIR,

  shellPath(doc: VeriDocument): string {
    return `${CLAUDE_SKILLS_DIR}/${skillName(doc)}/SKILL.md`;
  },

  emit(doc: VeriDocument): SkillShell {
    const name = skillName(doc);
    const description = doc.description ?? '';
    const requires = doc.requires ?? [];
    const methodFile = `veri/${doc.file}`;
    const lines = [
      '---',
      `name: ${name}`,
      `description: ${yamlString(description)}`,
      '---',
      '',
      SHELL_MARKER,
      '',
      `This file is a pointer, not the method. The method is the Veri document **${doc.id}**, at \`${methodFile}\`.`,
      '',
      `Before doing anything else, read it: fetch \`${doc.id}\` with the \`get_document\` MCP tool, or open the file. Follow what it says; nothing in this file substitutes for it.`,
      '',
      requires.length === 0
        ? 'This gate declares no required MCP tools.'
        : `This gate cannot run without these MCP tools: ${requires.map((tool) => `\`${tool}\``).join(', ')}. If any is missing from the connected Veri server, stop and say which one — never interview a user and then have nowhere to file the result.`,
      '',
      'Everything filed here is `draft`/`proposed`. Promotion is the user\'s act (REQ-008).',
      '',
    ];
    return { path: this.shellPath(doc), name, methodId: doc.id, content: lines.join('\n') };
  },

  owns(path: string): boolean {
    return new RegExp(`^${CLAUDE_SKILLS_DIR.replace(/\./g, '\\.')}/[^/]+/SKILL\\.md$`).test(path.replaceAll('\\', '/'));
  },
};

/** Every emitter this build can write, by harness id. A second harness is an
    entry here plus its `SkillEmitter`; nothing else changes (DEC-125). */
export const SKILL_EMITTERS: Record<string, SkillEmitter> = {
  [claudeCodeEmitter.harness]: claudeCodeEmitter,
};

/** A shell the host found on disk, as collected. */
export interface CollectedShell {
  /** Repo-root-relative, forward slashes. */
  path: string;
  content: string;
}

/** A method that will not get a shell, and why — reported, never silent. */
export interface SkippedMethod {
  id: string;
  title: string;
  reason: string;
}

/** A shell that should go, and why. */
export interface StaleShell {
  path: string;
  reason: string;
}

export interface SkillInstallPlan {
  harness: string;
  directory: string;
  /** Shells to create or refresh. */
  write: SkillShell[];
  /** Shells already byte-identical to what the method emits now. */
  unchanged: SkillShell[];
  /** Generated shells whose method left play — removed, never orphaned. */
  remove: StaleShell[];
  /** Accepted methods deliberately not emitted, and non-accepted ones. */
  skipped: SkippedMethod[];
  /** True when the plan would change nothing on disk. */
  noop: boolean;
}

export interface SkillInstallOptions {
  /** Which harness to emit for. Defaults to Claude Code (DEC-125). */
  emitter?: SkillEmitter;
  /** Emit for every accepted method, advanced tier included. */
  all?: boolean;
}

/**
 * What `veri skills install` would do — computed, not done.
 *
 * The rules, in the order they matter:
 *
 * - Only `accepted` methods are emitted at all. `draft` and `retired` (and
 *   `withdrawn`) never get a shell (DEC-130).
 * - A shell that already exists for an accepted method is refreshed when its
 *   content differs and left alone when it does not — which is what makes a
 *   second run a reported no-op.
 * - Tier gates *creation* only, never refresh and never removal. A project
 *   that asked for an advanced shell keeps it current; a default install does
 *   not silently take it away.
 * - A generated shell whose method is no longer accepted is removed. Only
 *   files carrying `SHELL_MARKER` are ever removed, so a hand-authored skill
 *   in the same directory survives.
 */
export function planSkillInstall(
  documents: VeriDocument[],
  existing: CollectedShell[],
  opts: SkillInstallOptions = {},
): SkillInstallPlan {
  const emitter = opts.emitter ?? claudeCodeEmitter;
  const onDisk = new Map(existing.map((shell) => [shell.path.replaceAll('\\', '/'), shell.content]));

  const write: SkillShell[] = [];
  const unchanged: SkillShell[] = [];
  const skipped: SkippedMethod[] = [];
  const targets = new Set<string>();

  const methods = documents.filter((doc) => doc.type === 'method');
  for (const doc of methods.slice().sort((a, b) => (a.id < b.id ? -1 : a.id > b.id ? 1 : 0))) {
    if (!isEmittable(doc)) {
      skipped.push({
        id: doc.id,
        title: doc.title,
        reason: `status ${doc.status} — only an accepted method gets a shell, so a gate can never trigger before it has been read (DEC-130)`,
      });
      continue;
    }
    const shell = emitter.emit(doc);
    targets.add(shell.path);
    const current = onDisk.get(shell.path);
    if (current === shell.content) {
      unchanged.push(shell);
      continue;
    }
    if (current === undefined && !(opts.all === true) && !isDefaultTier(doc)) {
      skipped.push({
        id: doc.id,
        title: doc.title,
        reason: 'advanced tier — not in the default set REQ-040 enumerates; install it with --all',
      });
      continue;
    }
    write.push(shell);
  }

  const remove: StaleShell[] = [];
  for (const [path, content] of [...onDisk].sort(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0))) {
    if (targets.has(path)) continue;
    if (!emitter.owns(path)) continue;
    if (!content.includes(SHELL_MARKER)) continue;
    remove.push({
      path,
      reason: 'the method behind it is no longer an accepted method of this project — the document and its inbound [[MET-nnn]] links are untouched',
    });
  }

  return {
    harness: emitter.harness,
    directory: emitter.directory,
    write,
    unchanged,
    remove,
    skipped,
    noop: write.length === 0 && remove.length === 0,
  };
}

// --- Upgrade by proposal (DEC-125) -----------------------------------------

/**
 * One method as Veri ships it: the upgradeable payload and nothing else.
 *
 * Ids, statuses, dates, and links are deliberately not here. They are the
 * project's, not the library's — an id is minted per project, a status is the
 * user's verdict, and a shipped document's links point at Veri's own graph.
 * What an upgrade can honestly propose is the coaching itself.
 */
export interface ShippedMethod {
  /** The stable slug an `upstream:` names, e.g. `product-discovery`. */
  slug: string;
  /** The full `upstream:` value, e.g. `veri/product-discovery`. */
  upstream: string;
  title: string;
  description: string;
  requires: string[];
  body: string;
}

/** Read the shipped payload out of a parsed method document. */
export function shippedMethodFrom(doc: VeriDocument): ShippedMethod {
  const upstream = (doc.upstream ?? '').trim();
  if (upstream === '') throw new Error(`${doc.id} (${doc.file}) has no upstream: — a shipped method is identified by its upstream slug (DEC-130)`);
  return {
    slug: methodSlug(doc),
    upstream,
    title: doc.title,
    description: doc.description ?? '',
    requires: doc.requires ?? [],
    body: doc.body,
  };
}

/** A reviewable proposal: the shipped text, written where the user can read
    it, with the project's own method untouched. */
export interface MethodAmendment {
  /** The project method this is about. */
  id: string;
  /** That method's file, veri/-relative. */
  methodFile: string;
  upstream: string;
  /** Which fields differ: `description`, `requires`, `body`. */
  changed: string[];
  /** Where the proposal goes, veri/-relative. */
  file: string;
  content: string;
}

export interface MethodUpgradePlan {
  amendments: MethodAmendment[];
  /** Project methods already matching what this build ships. */
  upToDate: string[];
  /** Methods with no `upstream:` — the project's own, never touched. */
  own: string[];
  /** Methods whose `upstream:` names nothing this build ships. */
  unmatched: Array<{ id: string; upstream: string }>;
  /** Shipped slugs this project has no method for — named, never written. */
  absent: string[];
  noop: boolean;
}

function sameRequires(a: string[], b: string[]): boolean {
  return a.length === b.length && a.every((tool, at) => tool === b[at]);
}

/** Bodies compare on trailing whitespace only — a stray blank line at the end
    of a file is not a difference anybody wants proposed back to them. */
function sameBody(a: string, b: string): boolean {
  return a.trimEnd() === b.trimEnd();
}

function amendmentText(doc: VeriDocument, shipped: ShippedMethod, changed: string[]): string {
  return [
    `# Proposed amendment — ${doc.id}`,
    '',
    `\`veri skills upgrade\` compared this project's copy of the shipped method \`${shipped.upstream}\` against the version bundled with this build of Veri, and found differences in: ${changed.join(', ')}.`,
    '',
    `**Nothing was changed.** \`veri/${doc.file}\` is exactly as it was. This file is a proposal, not canon: it carries no id, it is not part of the document graph, and it binds nothing (DEC-125 — an agent proposes, the user promotes).`,
    '',
    'To take any of it, edit the method document yourself and then delete this file. To decline, delete this file: drift from the shipped method is permitted, and a project that has tuned how its gate runs keeps that tuning.',
    '',
    '## Shipped `description:`',
    '',
    shipped.description,
    '',
    '## Shipped `requires:`',
    '',
    ...(shipped.requires.length === 0 ? ['(none)'] : shipped.requires.map((tool) => `- ${tool}`)),
    '',
    '## Shipped body',
    '',
    shipped.body.trim(),
    '',
  ].join('\n');
}

/**
 * What `veri skills upgrade` would propose — computed, not done.
 *
 * Matching is on `upstream:` and on nothing else. DEC-130 rules out the id
 * (minted per project), the title, and the filename (both things the user is
 * invited to edit) precisely because all three break at the moment the
 * project has made the method its own — which is the case upgrade-by-proposal
 * exists to serve. A method with no `upstream:` is the project's own and is
 * left completely alone, including one whose title matches a shipped method
 * exactly.
 */
export function planMethodUpgrade(documents: VeriDocument[], shipped: ShippedMethod[]): MethodUpgradePlan {
  const library = new Map(shipped.map((entry) => [entry.upstream, entry]));
  const amendments: MethodAmendment[] = [];
  const upToDate: string[] = [];
  const own: string[] = [];
  const unmatched: Array<{ id: string; upstream: string }> = [];
  const matched = new Set<string>();

  const methods = documents
    .filter((doc) => doc.type === 'method')
    .slice()
    .sort((a, b) => (a.id < b.id ? -1 : a.id > b.id ? 1 : 0));

  for (const doc of methods) {
    const upstream = (doc.upstream ?? '').trim();
    if (upstream === '') {
      own.push(doc.id);
      continue;
    }
    const entry = library.get(upstream);
    if (entry === undefined) {
      unmatched.push({ id: doc.id, upstream });
      continue;
    }
    matched.add(upstream);
    const changed: string[] = [];
    if ((doc.description ?? '') !== entry.description) changed.push('description');
    if (!sameRequires(doc.requires ?? [], entry.requires)) changed.push('requires');
    if (!sameBody(doc.body, entry.body)) changed.push('body');
    if (changed.length === 0) {
      upToDate.push(doc.id);
      continue;
    }
    amendments.push({
      id: doc.id,
      methodFile: doc.file,
      upstream,
      changed,
      file: `${AMENDMENTS_DIR}/${doc.id}-${entry.slug}.md`,
      content: amendmentText(doc, entry, changed),
    });
  }

  const absent = shipped
    .filter((entry) => !matched.has(entry.upstream))
    .map((entry) => entry.upstream)
    .sort();

  return { amendments, upToDate, own, unmatched, absent, noop: amendments.length === 0 };
}
